program tests

  ! Driver program for FRUIT unit tests in:
  ! test_02_fstrings.F90
  ! test_03_fstrings.F90

  ! Generated by FRUITPy.

  use fruit
  use test_02_fstrings
  use test_03_fstrings

  implicit none

  call init_fruit

  ! test_02_fstrings.F90:
  call run_test_case(test_sort_routine,"sort FSTRINGS_T objects and extract correct values")

  ! test_03_fstrings.F90:
  call run_test_case(test_split_function_to_generate_list_from_string,"create FSTRINGS_T objects from delimited character strings")

  call fruit_summary
  call fruit_finalize

end program tests