program tests

  ! Driver program for FRUIT unit tests in:
  ! test_01_fstrings.F90
  ! test_02_fstrings.F90
  ! test_03_fstrings.F90
  ! test_04_fstrings.F90
  ! test__fstrings__contains.F90
  ! test__fstrings__unique.F90

  ! Generated by FRUITPy.

  use fruit
  use test_01_fstrings
  use test_02_fstrings
  use test_03_fstrings
  use test_04_fstrings
  use test__fstrings__count_matching
  use test__fstrings__unique

  implicit none

  call init_fruit

  ! test_01_fstrings.F90:
  call run_test_case(test_count_function,"create FSTRINGS_T objects from delimited character strings")

  ! test_02_fstrings.F90:
  call run_test_case(test_sort_routine,"sort FSTRINGS_T objects and extract correct values")

  ! test_03_fstrings.F90:
  call run_test_case(test_split_function_to_generate_list_from_string,"create FSTRINGS_T objects from delimited character strings")

  ! test_04_fstrings.F90:
  call run_test_case(test_grep_function,"create FSTRINGS_T objects from delimited character strings")

  ! test__fstrings__contains.F90:
  call run_test_case(test_count_matching_function,"create FSTRINGS_T objects from delimited character strings")

  ! test__fstrings__unique.F90:
  call run_test_case(test_unique_function,"create FSTRINGS_T objects from delimited character strings")

  call fruit_summary
  call fruit_finalize

end program tests