program tests

  ! Driver program for FRUIT unit tests in:
  ! test__fstrings__append_list.F90
  ! test__fstrings__chomp.F90
  ! test__fstrings__contains.F90
  ! test__fstrings__conversions.F90
  ! test__fstrings__count_entries.F90
  ! test__fstrings__grep.F90
  ! test__fstrings__grep_2.F90
  ! test__fstrings__replace.F90
  ! test__fstrings__sort.F90
  ! test__fstrings__split_generate_list.F90
  ! test__fstrings__string_operators.F90
  ! test__fstrings__unique.F90

  ! Generated by FRUITPy.

  use fruit
  use test__fstrings__append_list
  use test__fstrings__chomp
  use test__fstrings__count_matching
  use test__fstrings__conversions
  use test__fstrings__count_entries
  use test__fstrings__grep
  use test__fstrings__grep_2
  use test__fstrings__replace
  use test__fstrings__sort
  use test__fstrings__split_generate_list
  use test__fstrings__string_operators
  use test__fstrings__unique

  implicit none

  call init_fruit

  ! test__fstrings__append_list.F90:
  call run_test_case(test_append_list_function,"append one FSTRING_LIST_T object to another FSTRING_LIST_T object")
  call run_test_case(test_append_list_missing_values,"create FSTRING_LIST_T objects appended w missing values")
  call run_test_case(test_detect_missing_values,"test whether empty list entries are detected and counted")

  ! test__fstrings__chomp.F90:
  call run_test_case(test_chomp,"test 'chomp' subroutine")

  ! test__fstrings__contains.F90:
  call run_test_case(test_count_matching_function,"create FSTRING_LIST_T objects from delimited character strings")

  ! test__fstrings__conversions.F90:
  call run_test_case(test_c_double_conversions,"test as_character for c_double value")
  call run_test_case(test_float_conversions,"test as_character for c_float value")
  call run_test_case(test_short_conversions,"test as_character for c_short value")
  call run_test_case(test_integer_conversions,"test as_character for c_int value")

  ! test__fstrings__count_entries.F90:
  call run_test_case(test_count_function,"create FSTRING_LIST_T objects from delimited character strings")

  ! test__fstrings__grep.F90:
  call run_test_case(test_grep_function,"create FSTRING_LIST_T 'grep' functionality")

  ! test__fstrings__grep_2.F90:
  call run_test_case(test_grep_function_2,"test partial string matching in FSTRING_LIST_T 'grep' functionality")

  ! test__fstrings__replace.F90:
  call run_test_case(test_replace,"test 'chomp' subroutine")

  ! test__fstrings__sort.F90:
  call run_test_case(test_sort_routine,"sort FSTRING_LIST_T objects and extract correct values")

  ! test__fstrings__split_generate_list.F90:
  call run_test_case(test_generate_list_from_delimited_string,"create FSTRING_LIST_T objects from delimited character strings")
  call run_test_case(test_append_list_string_missing_values,"create FSTRING_LIST_T objects from appended list w missing values")
  call run_test_case(test_generate_list_string_missing_values,"create FSTRING_LIST_T objects from split list w missing values")

  ! test__fstrings__string_operators.F90:
  call run_test_case(test_integer_concat,"append integer value to a string")
  call run_test_case(test_float_concat,"append float value to a string")
  call run_test_case(test_double_concat,"append double value to a string")
  call run_test_case(test_char_concat,"append double value to a string")
  call run_test_case(test_contains_operator,"test .contains. operator")
  call run_test_case(test_containssimilar_operator,"test .containssimilar. operator")
  call run_test_case(test_strequal_operator,"test .contains. operator")
  call run_test_case(test_strapprox_operator,"test .contains. operator")

  ! test__fstrings__unique.F90:
  call run_test_case(test_unique_function,"pare a list with duplicates down to a unique list")

  call fruit_summary
  call fruit_finalize

end program tests